### ISSUE TITLE
[Windows10 | Electron 8.2.1] Path is wrong when app is packed in .asar archive

### ISSUE THREAD

**Issue by c-buzz** [ganeshrvel/npm-electron-root-path#2]
Tested on Windows10, Electron 8.2.1 - App packed with [electron-packager](https://github.com/electron/electron-packager)
When app is packed in an `app.asar` archive, the module returns a `rootPath` pointing to the folder where the executable, not the archive, is.

Digging into the source code I found `isPacked` works fine, so the lib is capable to discern the packaging. 
On my PC/version/packager I resolved the following way in `index.js`
```
if (isPackaged) {
      // renderer and main process - packaged build
  if (electronEnv.isWindows) {
    // windows platform
    rootPath = path.join(__dirname, '..', '../../')  // -- MY VERSION
    // rootPath = path.join(__dirname, '..', '../../../../');  -- ORIGINAL
  } else {
    // non windows platform
    rootPath = path.join(__dirname, '..', '../../../../../');
 }
```

I will update the issue if I have the opportunity to test on `linux`

**Comment by ganeshrvel** [comment]
Could you open a pr for the same?

Hi,



Regards,
Ganesh Rathinavel

________________________________

**Comment by c-buzz** [comment]
First time I process a pr. Hope I've done it correct way

**Comment by ganeshrvel** [comment]
I believe this is happening because of typescript. If anyone else is facing this issue upgrade the package to [>= 1.1.0](https://www.npmjs.com/package/electron-root-path)
